### ISSUE TITLE
Branch name size is over 100 chars

### ISSUE THREAD

**Issue by shalev007** [LironEr/bundlemon-action#23]
Hey why are you checking the branch name size
![image](https://github.com/LironEr/bundlemon-action/assets/51760613/eaa9cc0f-3805-4e46-9028-ac491b2ce659)

**Comment by LironEr** [comment]
There is a limit in GitHub of around 250 characters (depending on the encoding)

Also, the DB of BundleMon has an index on `branch` so I didn't want to allow a very long name because it will use more storage..
Anyway I will increase it to 200, which should be more than enough

**Comment by LironEr** [comment]
The service with the change has been deployed, you don't need to change anything, just run again.
